baseurl: /
markdown: kramdown
permalink: /:year/:month/:day/:title/
timezone: Asia/Shanghai

home: http://www.vovicn.com/
demo: http://www.vovicn.com/
base: https://yocobear.github.io/snippets
weibo: http://www.vovicn.com/
edit_path: https://github.com/yocobear/snippets/edit/gh-pages
new_path: https://github.com/yocobear/snippets/new/gh-pages/snippets
author: yocoyang
author_en: Yoco Yang
email: yocoyang@163.com
author_info: <a href="http://www.vovicn.com">Yoco Yang</a>

webrick:
  headers:
    Author: Yoco Yang
    About: http://vovocn.com/about/

gems:
  - jekyll-seo-tag
#  - jekyll-feed

# seo
twitter:
  username: yocoyang
logo: http://www.barretlee.com/avatar150.png

# feed
# feed:
#   path: atom.xml
#   name: Snippets
#   description: 小胡子哥的代码收藏夹，Snippets 管理工具
#   url: http://snippets.barretlee.com
#   author: 小胡子哥

defaults:
  -
    scope:
      path: "snippets"
      type: "posts"
    values:
      layout: nil
